version: '3'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    volumes:
      - ./mariaDB:/var/lib/mysql  
    networks:
      - wordpress_network

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    volumes:
      - wordpress_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    networks:
      - wordpress_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx:/var/www/html
      - nginx_conf:/etc/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_files:
  nginx_conf:
